config/routes.rb
Rails.application.routes.draw do
  # resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    if params['completed'] == 1
      params['completed'] = true
    elsif params['completed'] == 1
      params['completed'] = false
    end
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to tasks_path
  end

  def delete
    task = Task.find(params[:id])
    task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task, :method => "patch") do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title  %>
  <%= f.label :details %>
  <%= f.text_field :details  %>
  <%= f.label :completed %>
  <%= f.check_box :completed  %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>My tasks</h2>
<ul>
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <div class="item">
        <li class="checked element"> <%= link_to task.title, "/tasks/#{task.id}" %>  </li>
        <p class="element"> <%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: "Delete #{task.title}"} %> </p>
      </div>
      <% else %>
      <div class="item">
        <li class="element"> <%= link_to task.title, "/tasks/#{task.id}" %> </li>
        <p class="element"> <%= link_to 'Delete', task_path(task), method: :delete, data: {confirm: "Delete #{task.title}"} %> </p>
      </div>
    <% end %>
  <% end %>
</ul>
<%= link_to "Add a new task", "/tasks/new" %>

app/views/tasks/new.html.erb
<h2>New Task</h2>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title  %>
  <%= f.label :details %>
  <%= f.text_field :details  %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2> <%= @task.title %> </h2>
<p> <%= @task.details %></p>
<%= link_to "Back to list", "/tasks"%>
<%= link_to "Edit this task", edit_task_path(@task) %>